### ISSUE TITLE
Diversity and inclusion language change in src/processor/stackwalker_x86_unittest.cc

### ISSUE THREAD

**Issue by toddsaharchukskyboxlabs** [microsoft/appcenter-sdk-android-breakpad#8]
There are 2 occurrences of 'grandfather' in the comments within src/processor/stackwalker_x86_unittest.cc
Suggestion to change to 'carry over' or similar.

**Comment by russelarms** [comment]
Hi, thanks for reaching out!
It's a forked repo, maybe it'll make more sense to suggest this change to the main repository: https://chromium.googlesource.com/breakpad/breakpad

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
